baseurl: /coq-examples
exclude:
  - content

all_tags:
  - classical
  - coercion
  - complete
  - compute
  - congruence
  - convoy-pattern
  - decidable
  - eq_rect
  - fixpoint
  - indexed-type
  - match
  - module
  - nested
  - notation
  - proof-irrelevance
  - proving
  - record
  - reflection
  - sigma-type
  - synthesis
  - tactic
  - typeclass
  - universe
  - view-pattern
  - well-founded
