baseurl: /coq-examples
exclude:
  - content

all_tags:
  - classical
  - coercion
  - compute
  - congruence
  - convoy-pattern
  - decidable
  - eq_rect
  - fixpoint
  - indexed-type
  - match
  - module
  - proof-irrelevance
  - proving
  - record
  - reflection
  - sigma-type
  - tactic
  - universe
  - view
