#!/usr/bin/env bash

DATA_DIRS="examples notes"
ROOT_DIR=$(dirname "$0")/..

for data_dir in ${DATA_DIRS}; do
    data_path=${ROOT_DIR}/public/_data/${data_dir}.yml
    [[ -f $data_path ]] || touch "$data_path"

    temp_data=$(mktemp --tmpdir data.yml.XXXXXX)
    trap "rm -f $temp_data" EXIT

    start=true
    for src_path in "${ROOT_DIR}/${data_dir}"/*.v; do
        # Separate sections
        $start || echo >> "$temp_data"
        start=false

        basename=${src_path##*/}
        dst_file=${basename%.v}.html
        section=$(sed -En "/${dst_file}/,/^ *$/p" "$data_path")

        if [[ -n $section ]]; then
            echo "$section" >> "$temp_data"
        else
            title=$(sed -En '/^#+$/,/^#+$/p' "$src_path" | grep -Ev '^#+$')

            # Escape characters
            title=$(sed 's@"@\\"@g' <<< "$title")

            # Interpret inline code
            tmp_title=$title
            while [[ -n $tmp_title ]]; do
                title=$tmp_title
                tmp_title=$(sed -nE 's@(^|[^_0-9a-zA-Z])``@\1<tt>@p' <<< "$tmp_title")
                tmp_title=$(sed -nE 's@``($|[^_0-9a-zA-Z])@</tt>\1@p' <<< "$tmp_title")
            done
            title=$(sed 's@\\ @@g' <<< "$title")

            ( echo "- path: \"${data_dir}/${dst_file}\"";
              echo "  title: \"${title}\"" ) >> "$temp_data"
        fi
    done

    cp -f "$temp_data" "$data_path"
done

exit 0
